CREATE TABLE `order` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `seller_id` int(11) unsigned NOT NULL,
  `buyer_id` int(11) unsigned NOT NULL,
  `seller_token` tinytext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `buyer_token` tinytext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `amount_usd` bigint(20) unsigned NOT NULL,
  `amount_grm` bigint(20) unsigned NOT NULL,
  `address` tinytext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `product_id` int(11) unsigned NOT NULL,
  `privkey` text CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `paid` tinyint(1) NOT NULL DEFAULT '0',
  `released` tinyint(1) NOT NULL DEFAULT '0',
  `refunded` tinyint(1) NOT NULL DEFAULT '0',
  `dispute` tinyint(1) NOT NULL DEFAULT '0',
  `opened_time` bigint(20) NOT NULL,
  `paid_time` bigint(20) DEFAULT NULL,
  `price_usd` bigint(20) unsigned NOT NULL,
  `price_grm` bigint(20) unsigned NOT NULL,
  `buyer_rated` tinyint(1) NOT NULL DEFAULT '0',
  `seller_rated` tinyint(1) NOT NULL DEFAULT '0',
  `confirmed` tinyint(1) NOT NULL DEFAULT '0',
  `complete` tinyint(1) NOT NULL DEFAULT '0',
  `success` tinyint(1) NOT NULL DEFAULT '0',
  `key` int(32) NOT NULL DEFAULT '0',
  `token` tinytext CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=44 DEFAULT CHARSET=utf8